parameters:
- name: name
  type: string

variables:
  INIT_SCRIPT_URL: "https://raw.githubusercontent.com/mbivolan/mctv2/master/utils/setup_env.sh"

trigger: none
jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ubuntu-18.04
  strategy:
    matrix:
      node_12_x:
        node_version: 12.x
  steps:
    - task: AzureKeyVault@1
      displayName: 'Azure Key Vault: MCT-Secrets'
      inputs:
        azureSubscription: AzureConnection
        KeyVaultName: 'MCT-Secrets'
        SecretsFilter: RTConfigFile,RTCredentialGCP
    - task: Bash@3
      displayName: 'Installing Generic tools'
      inputs:
        targetType: 'inline'
        script: |
          curl -sL $(INIT_SCRIPT_URL) | sudo bash
    - task: NodeTool@0 
      inputs:
        versionSpec: $(node_version)
    - task: Bash@3
      displayName: 'Running the query'
      inputs:
        targetType: 'inline'
        script: |
          set -x
          pwd
          ls
          mkdir -p /tmp/results/
          wget "$(RTConfigFile)" -O /tmp/config.json

          wget "$(RTCredentialGCP)" -O /tmp/secrets.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/secrets.json"

          npm install
          node main.js -c /tmp/config.json -o /tmp/results
    - task: Bash@3
      displayName: 'CSCC_0 logs'
      inputs:
        targetType: 'inline'
        script: |
          cat /tmp/results/CSCC_0.json
    - task: Bash@3
      displayName: 'Qualys_0 logs'
      inputs:
        targetType: 'inline'
        script: |
          cat /tmp/results/Qualys_0.json
    - task: Bash@3
      displayName: 'Qualys_1 logs'
      inputs:
        targetType: 'inline'
        script: |
          cat /tmp/results/Qualys_1.json